name: Build Commit

on:
  push:
    paths:
      - ".github/workflows/build-commit.yml"
      - "src/**"
      - "HyperSharp.sln"

env:
  DOTNET_NOLOGO: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1

permissions:
  actions: write

jobs:
  build_commit:
    name: Build Commit ${{ github.sha }}
    runs-on: self-hosted
    if: "!contains(format('{0} {1}', github.event.head_commit.message, github.event.pull_request.title), '[ci-skip]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8
      - name: Build Project
        run: dotnet build
      - name: Test Project
        run: dotnet run -c Release --project tests/HyperSharp.Tests.csproj >/dev/null
      - name: Output Test Results
        id: test-results
        run: |
          body="$(cat BenchmarkDotNet.Artifacts/results/OoLunar.HyperSharp.Tests.Benchmarks.Benchmarks.ConcurrentRequests-report-github.md)"
          delimiter="$(openssl rand -hex 8)"
          echo "body<<$delimiter" >> $GITHUB_OUTPUT
          echo "$body" >> $GITHUB_OUTPUT
          echo "$delimiter" >> $GITHUB_OUTPUT
      - name: Comment Results
        uses: peter-evans/commit-comment@v2
        with:
          body: ${{ steps.test-results.outputs.body }}
          token: ${{ secrets.GITHUB_TOKEN }}